#!/bin/sh

# config system
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.led_wan
uci commit system

# config wireless
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.ssid="${WIRELESS_NAME}_5G"
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key="$WIRELESS_PWD"
uci set wireless.radio1.disabled='0'
uci set wireless.default_radio1.ssid="$WIRELESS_NAME"
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key="$WIRELESS_PWD"
# uci set wireless.default_radio1.macfilter='deny'
uci commit wireless
# sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

# config extra storage
uci set fstab.@mount[0].target='/overlay'
uci commit fstab

exit 0
